[versions]
agp = "8.13.0"
core = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
itext7 = "8.0.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
itext7-kernel = { group = "com.itextpdf", name = "kernel", version.ref = "itext7" }
itext7-io = { group = "com.itextpdf", name = "io", version.ref = "itext7" }
itext7-layout = { group = "com.itextpdf", name = "layout", version.ref = "itext7" }
