[versions]
agp = "8.13.0"
kotlin = "2.1.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
itext7 = "8.0.5"
commonmark = "0.24.0"
itext7-html2pdf = "5.0.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
itext7-kernel = { group = "com.itextpdf", name = "kernel", version.ref = "itext7" }
itext7-io = { group = "com.itextpdf", name = "io", version.ref = "itext7" }
itext7-layout = { group = "com.itextpdf", name = "layout", version.ref = "itext7" }
itext7-html2pdf = { group = "com.itextpdf", name = "html2pdf", version.ref = "itext7-html2pdf" }
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
commonmark-tables = { group = "org.commonmark", name = "commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmark-strikethrough = { group = "org.commonmark", name = "commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmark-tasklist = { group = "org.commonmark", name = "commonmark-ext-task-list-items", version.ref = "commonmark" }
commonmark-autolink = { group = "org.commonmark", name = "commonmark-ext-autolink", version.ref = "commonmark" }
commonmark-ins = { group = "org.commonmark", name = "commonmark-ext-ins", version.ref = "commonmark" }
